# Generated by Django 3.0.8 on 2020-07-18 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('reason', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('supply_date', models.DateField()),
                ('supplier', models.CharField(max_length=250)),
                ('vat', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('sub_total', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('freight_charge', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SupplyLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('expiry_date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('lot_number', models.CharField(max_length=100)),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=19)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Drug')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply_lines', to='inventory.Supply')),
            ],
        ),
        migrations.CreateModel(
            name='StockAdjustmentLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('lot_number', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Drug')),
                ('stock_adjustment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.StockAdjustment')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('lot_number', models.CharField(max_length=100)),
                ('expiry_date', models.DateField()),
                ('quantity', models.IntegerField(default=0)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Drug')),
            ],
        ),
    ]
