# Generated by Django 3.0.6 on 2020-05-21 23:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_allergy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=19)),
                ('cost_price_per_pack', models.DecimalField(decimal_places=2, max_digits=19)),
                ('quantity_per_pack', models.IntegerField(default=1)),
            ],
        ),
    ]
