# Generated by Django 3.0.6 on 2020-05-30 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('sub_total', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('timestamp', models.DateTimeField()),
                ('attendant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SaleLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Drug')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_lines', to='dispensary.Sale')),
            ],
        ),
    ]
